#!/usr/bin/env python3
"""Generate diagrams for surface-frame WGS84 trajectory propagation.

The diagrams are deterministic SVG assets for the companion HTML document.
Geometric diagrams use WGS 84 constants and explicit ECEF/local-frame formulas;
the workflow diagram is generated by the same script so the document remains
reproducible.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import escape
from math import cos, pi, sin, sqrt
from pathlib import Path
from typing import Iterable, Sequence


WGS84_A_M = 6_378_137.0
WGS84_INV_F = 298.257223563
WGS84_F = 1.0 / WGS84_INV_F
WGS84_E2 = WGS84_F * (2.0 - WGS84_F)
WGS84_B_OVER_A = 1.0 - WGS84_F

TEACHING_PHI_DEG = 49.1939
TEACHING_LAMBDA_DEG = -123.1844
TEACHING_PHI = TEACHING_PHI_DEG * pi / 180.0
TEACHING_LAMBDA = TEACHING_LAMBDA_DEG * pi / 180.0
VISUAL_H_OVER_A = 0.105

ASSET_DIR = Path(__file__).resolve().parent / "assets" / "surface_frame_propagation"

Vec3 = tuple[float, float, float]
Vec2 = tuple[float, float]


def dot(a: Vec3, b: Vec3) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a: Vec3, b: Vec3) -> Vec3:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def norm(v: Vec3) -> float:
    return sqrt(dot(v, v))


def unit(v: Vec3) -> Vec3:
    n = norm(v)
    return (v[0] / n, v[1] / n, v[2] / n)


def add(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def mul(s: float, v: Vec3) -> Vec3:
    return (s * v[0], s * v[1], s * v[2])


def nu_over_a(phi: float) -> float:
    return 1.0 / sqrt(1.0 - WGS84_E2 * sin(phi) ** 2)


def meridian_radius_over_a(phi: float) -> float:
    return (1.0 - WGS84_E2) / (1.0 - WGS84_E2 * sin(phi) ** 2) ** 1.5


def geodetic_unit(phi: float, lam: float, h_over_a: float = 0.0) -> Vec3:
    nu = nu_over_a(phi)
    return (
        (nu + h_over_a) * cos(phi) * cos(lam),
        (nu + h_over_a) * cos(phi) * sin(lam),
        ((1.0 - WGS84_E2) * nu + h_over_a) * sin(phi),
    )


def east_unit(lam: float) -> Vec3:
    return (-sin(lam), cos(lam), 0.0)


def north_unit(phi: float, lam: float) -> Vec3:
    return (-sin(phi) * cos(lam), -sin(phi) * sin(lam), cos(phi))


def up_unit(phi: float, lam: float) -> Vec3:
    return (cos(phi) * cos(lam), cos(phi) * sin(lam), sin(phi))


def ellipsoid_lat(phi: float, samples: int = 145) -> list[Vec3]:
    return [geodetic_unit(phi, 2.0 * pi * i / (samples - 1)) for i in range(samples)]


def ellipsoid_lon(lam: float, samples: int = 121) -> list[Vec3]:
    return [geodetic_unit(-pi / 2.0 + pi * i / (samples - 1), lam) for i in range(samples)]


def wire_points() -> list[Vec3]:
    pts: list[Vec3] = []
    for phi_deg in (-60, -30, 0, 30, 60):
        pts.extend(ellipsoid_lat(phi_deg * pi / 180.0))
    for lam_deg in (-135, -90, -45, 0, 45, 90, 135, 180, TEACHING_LAMBDA_DEG):
        pts.extend(ellipsoid_lon(lam_deg * pi / 180.0))
    return pts


@dataclass
class Camera:
    eye: Vec3 = (1.9, -2.5, 1.25)

    def __post_init__(self) -> None:
        self.view = unit(self.eye)
        self.x_axis = unit(cross((0.0, 0.0, 1.0), self.view))
        self.y_axis = unit(cross(self.view, self.x_axis))

    def raw_project(self, p: Vec3) -> Vec2:
        return (dot(p, self.x_axis), dot(p, self.y_axis))


class Svg:
    def __init__(
        self,
        width: int,
        height: int,
        title: str,
        world_points: Sequence[Vec3],
        camera: Camera | None = None,
        pad: int = 58,
    ) -> None:
        self.width = width
        self.height = height
        self.title = title
        self.camera = camera or Camera()
        raws = [self.camera.raw_project(p) for p in world_points]
        xs = [p[0] for p in raws]
        ys = [p[1] for p in raws]
        x_span = max(xs) - min(xs) or 1.0
        y_span = max(ys) - min(ys) or 1.0
        self.scale = min((width - 2 * pad) / x_span, (height - 2 * pad) / y_span)
        self.x_mid = (max(xs) + min(xs)) / 2.0
        self.y_mid = (max(ys) + min(ys)) / 2.0
        self.items: list[str] = []

    def p(self, world: Vec3) -> Vec2:
        x, y = self.camera.raw_project(world)
        return (
            self.width / 2.0 + (x - self.x_mid) * self.scale,
            self.height / 2.0 - (y - self.y_mid) * self.scale,
        )

    def line(self, a: Vec3, b: Vec3, cls: str, marker: bool = False) -> None:
        ax, ay = self.p(a)
        bx, by = self.p(b)
        marker_attr = ' marker-end="url(#arrow)"' if marker else ""
        self.items.append(
            f'<line class="{cls}" x1="{ax:.1f}" y1="{ay:.1f}" x2="{bx:.1f}" y2="{by:.1f}"{marker_attr}/>'
        )

    def polyline(self, pts: Iterable[Vec3], cls: str) -> None:
        pairs = " ".join(f"{x:.1f},{y:.1f}" for x, y in (self.p(p) for p in pts))
        self.items.append(f'<polyline class="{cls}" points="{pairs}"/>')

    def polygon(self, pts: Iterable[Vec3], cls: str) -> None:
        pairs = " ".join(f"{x:.1f},{y:.1f}" for x, y in (self.p(p) for p in pts))
        self.items.append(f'<polygon class="{cls}" points="{pairs}"/>')

    def circle(self, p: Vec3, r: float, cls: str) -> None:
        x, y = self.p(p)
        self.items.append(f'<circle class="{cls}" cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}"/>')

    def text(self, text: str, p: Vec3, dx: float, dy: float, cls: str = "label") -> None:
        x, y = self.p(p)
        self.items.append(
            f'<text class="{cls}" x="{x + dx:.1f}" y="{y + dy:.1f}">{escape(text)}</text>'
        )

    def text_xy(self, text: str, x: float, y: float, cls: str = "label") -> None:
        self.items.append(f'<text class="{cls}" x="{x:.1f}" y="{y:.1f}">{escape(text)}</text>')

    def raw(self, item: str) -> None:
        self.items.append(item)

    def render(self) -> str:
        return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.width} {self.height}" role="img" aria-labelledby="title">
  <title id="title">{escape(self.title)}</title>
  <defs>
    <marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth">
      <path d="M0,0 L8,3 L0,6 Z" fill="#263548"/>
    </marker>
  </defs>
  <style>
    svg {{ background: linear-gradient(180deg, #fbfdff 0%, #f3f7fa 100%); }}
    .title {{ fill: #16212f; font: 700 22px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .subtitle {{ fill: #5f6f7e; font: 500 13px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .wire {{ fill: none; stroke: #6aa7ad; stroke-width: 1.25; opacity: .55; }}
    .equator {{ fill: none; stroke: #b65b13; stroke-width: 2.2; }}
    .meridian {{ fill: none; stroke: #3d58a8; stroke-width: 2.0; }}
    .axis {{ stroke: #263548; stroke-width: 2.4; fill: none; }}
    .north {{ stroke: #2f62b7; stroke-width: 2.8; fill: none; }}
    .east {{ stroke: #007c89; stroke-width: 2.8; fill: none; }}
    .up {{ stroke: #9a4c10; stroke-width: 2.8; fill: none; }}
    .down {{ stroke: #8f3f71; stroke-width: 2.8; fill: none; stroke-dasharray: 7 5; }}
    .helper {{ stroke: #8292a4; stroke-width: 1.5; stroke-dasharray: 6 5; fill: none; }}
    .plane {{ fill: #f7e7d6; opacity: .6; stroke: #b65b13; stroke-width: 1.2; }}
    .point {{ fill: #007c89; stroke: white; stroke-width: 2.0; }}
    .surface {{ fill: #b65b13; stroke: white; stroke-width: 2.0; }}
    .label {{ fill: #16212f; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .small {{ fill: #4b5d70; font: 500 12.5px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .teal {{ fill: #006f79; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .orange {{ fill: #9a4c10; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .indigo {{ fill: #314b99; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .magenta {{ fill: #8f3f71; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    .formula {{ fill: #263548; font: 600 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }}
  </style>
  <rect width="100%" height="100%" fill="#fbfdff"/>
  {''.join(self.items)}
</svg>
"""


def svg_2d_header(width: int, height: int, title: str) -> list[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title">',
        f'<title id="title">{escape(title)}</title>',
        '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L8,3 L0,6 Z" fill="#263548"/></marker></defs>',
        """<style>
svg { background: linear-gradient(180deg, #fbfdff 0%, #f3f7fa 100%); }
.title { fill: #16212f; font: 700 22px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.subtitle { fill: #5f6f7e; font: 500 13px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.box { fill: white; stroke: #c8d4df; stroke-width: 1.4; }
.accent { fill: #e7f7f8; stroke: #207b84; stroke-width: 1.4; }
.warn { fill: #fff5e8; stroke: #c2712a; stroke-width: 1.4; }
.axis { stroke: #263548; stroke-width: 2.2; marker-end: url(#arrow); fill: none; }
.north { stroke: #2f62b7; stroke-width: 2.7; marker-end: url(#arrow); fill: none; }
.east { stroke: #007c89; stroke-width: 2.7; marker-end: url(#arrow); fill: none; }
.up { stroke: #9a4c10; stroke-width: 2.7; marker-end: url(#arrow); fill: none; }
.down { stroke: #8f3f71; stroke-width: 2.7; marker-end: url(#arrow); fill: none; stroke-dasharray: 7 5; }
.arrow { stroke: #263548; stroke-width: 2.0; marker-end: url(#arrow); fill: none; }
.helper { stroke: #8292a4; stroke-width: 1.4; stroke-dasharray: 6 5; fill: none; }
.surface { fill: #b65b13; stroke: white; stroke-width: 2.0; }
.point { fill: #007c89; stroke: white; stroke-width: 2.0; }
.label { fill: #16212f; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.small { fill: #4b5d70; font: 500 12.5px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.teal { fill: #006f79; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.orange { fill: #9a4c10; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.indigo { fill: #314b99; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.magenta { fill: #8f3f71; font: 650 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
.formula { fill: #263548; font: 600 12px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
</style>""",
        f'<rect width="{width}" height="{height}" fill="#fbfdff"/>',
    ]


def draw_wire(svg: Svg) -> None:
    for phi_deg in (-60, -30, 30, 60):
        svg.polyline(ellipsoid_lat(phi_deg * pi / 180.0), "wire")
    for lam_deg in (-135, -90, -45, 0, 45, 90, 135):
        svg.polyline(ellipsoid_lon(lam_deg * pi / 180.0), "wire")
    svg.polyline(ellipsoid_lat(0.0), "equator")
    svg.polyline(ellipsoid_lon(0.0), "meridian")
    svg.polyline(ellipsoid_lon(TEACHING_LAMBDA), "meridian")


def diagram_architecture() -> str:
    width, height = 980, 560
    out = svg_2d_header(width, height, "Surface-frame propagation architecture")
    out.append('<text class="title" x="34" y="42">总体思路：局部 surface frame 算动力学，WGS84/ECEF 保存轨迹位置</text>')
    out.append('<text class="subtitle" x="34" y="66">FAA ADM 2.8 的核心：平地球飞机方程仍在局部切平面里解释，地球曲率只进入位置传播</text>')
    boxes = [
        (42, 122, 212, 92, "当前全球位置", "φ, λ, h", "WGS84 geodetic"),
        (298, 122, 212, 92, "当前位置构造局部轴", "E,N,U 或 N,E,D", "surface frame"),
        (554, 122, 212, 92, "飞机动力学", "V, ψ, γ, bank, n, T", "local equations"),
        (298, 298, 212, 92, "局部速度分量", "v_E, v_N, v_U", "or Vx,Vy,-h_dot"),
        (554, 298, 212, 92, "曲率半径传播", "φ_dot, λ_dot, h_dot", "M, ν"),
        (810, 298, 128, 92, "输出轨迹", "WGS84/ECEF", "for Cesium"),
    ]
    for x, y, w, h, title, main, sub in boxes:
        cls = "accent" if "全球" in title or "输出" in title else "box"
        out.append(f'<rect class="{cls}" x="{x}" y="{y}" width="{w}" height="{h}" rx="8"/>')
        out.append(f'<text class="label" x="{x + 18}" y="{y + 30}">{escape(title)}</text>')
        out.append(f'<text class="teal" x="{x + 18}" y="{y + 56}">{escape(main)}</text>')
        out.append(f'<text class="small" x="{x + 18}" y="{y + 78}">{escape(sub)}</text>')
    arrows = [
        (254, 168, 296, 168),
        (510, 168, 552, 168),
        (660, 214, 410, 296),
        (510, 344, 552, 344),
        (766, 344, 808, 344),
    ]
    for x1, y1, x2, y2 in arrows:
        out.append(f'<path class="arrow" d="M{x1},{y1} L{x2},{y2}"/>')
    out.append('<text class="formula" x="74" y="468">不把 x,y 长期积在固定平面里；位置状态改成 φ,λ,h，或每步由 φ,λ,h 计算 ECEF r。</text>')
    out.append('<text class="formula" x="74" y="494">动力学仍然输出局部水平/竖直速度；传播层把这些速度转换成经纬度变化率。</text>')
    out.append('<text class="small" x="812" y="420">下一步：输出的 φ,λ,h 成为新的当前位置</text>')
    out.append("</svg>")
    return "\n".join(out)


def diagram_surface_frame() -> str:
    phi, lam = TEACHING_PHI, TEACHING_LAMBDA
    s = geodetic_unit(phi, lam)
    p = geodetic_unit(phi, lam, VISUAL_H_OVER_A)
    e = east_unit(lam)
    n = north_unit(phi, lam)
    u = up_unit(phi, lam)
    d = mul(-1.0, u)
    plane = [
        add(p, add(mul(-0.24, e), mul(-0.18, n))),
        add(p, add(mul(0.28, e), mul(-0.18, n))),
        add(p, add(mul(0.28, e), mul(0.22, n))),
        add(p, add(mul(-0.24, e), mul(0.22, n))),
    ]
    pts = wire_points() + [(0, 0, 0), (1.45, 0, 0), (0, 1.45, 0), (0, 0, 1.35), s, p]
    pts += [add(p, mul(0.36, e)), add(p, mul(0.32, n)), add(p, mul(0.26, u)), add(p, mul(0.24, d))]
    pts += plane
    svg = Svg(980, 640, "ECEF and moving surface frame", pts, pad=52)
    svg.text_xy("生成式 3D 图：ECEF 全局位置 + 随飞机移动的局部 surface frame", 30, 38, "title")
    svg.text_xy("局部轴方向由当前 φ,λ 决定；位置仍可用 WGS84 或 ECEF 表示", 30, 62, "subtitle")
    draw_wire(svg)
    for end, label in [((1.45, 0, 0), "X_ECEF"), ((0, 1.45, 0), "Y_ECEF"), ((0, 0, 1.35), "Z_ECEF")]:
        svg.line((0, 0, 0), end, "axis", True)
        svg.text(label, end, 10, 4)
    svg.polygon(plane, "plane")
    svg.line(s, p, "up", True)
    svg.line(p, add(p, mul(0.36, e)), "east", True)
    svg.line(p, add(p, mul(0.32, n)), "north", True)
    svg.line(p, add(p, mul(0.26, u)), "up", True)
    svg.line(p, add(p, mul(0.24, d)), "down", True)
    svg.circle(s, 5.8, "surface")
    svg.circle(p, 6.8, "point")
    svg.text("S: 椭球面法线脚点", s, -42, 88, "orange")
    svg.text("P(φ,λ,h): 飞机位置", p, 58, -30, "teal")
    svg.text("E / East", add(p, mul(0.36, e)), 62, -2, "teal")
    svg.text("N / North", add(p, mul(0.32, n)), -126, -24, "indigo")
    svg.text("U / Up", add(p, mul(0.26, u)), 18, -30, "orange")
    svg.text("D = -U (FAA NED z_s)", add(p, mul(0.24, d)), 90, 78, "magenta")
    svg.text_xy("FAA 2.8: surface frame = NED: x_s=N, y_s=E, z_s=D", 44, 565, "formula")
    svg.text_xy("本文也给出与你 simulator.py 对齐的 ENU 写法: x=E, y=N, h=U/altitude", 44, 590, "formula")
    return svg.render()


def diagram_rate_patch() -> str:
    phi, lam = TEACHING_PHI, TEACHING_LAMBDA
    h = 0.055
    dphi = 0.050
    dlam = 0.070
    p0 = geodetic_unit(phi, lam, h)
    p_n = geodetic_unit(phi + dphi, lam, h)
    p_e = geodetic_unit(phi, lam + dlam, h)
    e = east_unit(lam)
    n = north_unit(phi, lam)
    u = up_unit(phi, lam)
    m = meridian_radius_over_a(phi)
    nu = nu_over_a(phi)
    east_scale = (nu + h) * cos(phi) * dlam
    north_scale = (m + h) * dphi
    p_e_tan = add(p0, mul(east_scale, e))
    p_n_tan = add(p0, mul(north_scale, n))
    p_u = add(p0, mul(0.18, u))
    pts = wire_points() + [p0, p_n, p_e, p_e_tan, p_n_tan, p_u]
    svg = Svg(980, 620, "Geodetic rate patch", pts, pad=54)
    svg.text_xy("生成式 3D 图：局部速度如何变成 φ_dot、λ_dot、h_dot", 30, 38, "title")
    svg.text_xy("微小位移沿 North/East/Up 分解；曲率半径把“米/秒”换成“弧度/秒”", 30, 62, "subtitle")
    draw_wire(svg)
    svg.line(p0, p_n_tan, "north", True)
    svg.line(p0, p_e_tan, "east", True)
    svg.line(p0, p_u, "up", True)
    svg.line(p0, p_n, "helper")
    svg.line(p0, p_e, "helper")
    svg.circle(p0, 6.5, "point")
    svg.text("当前 P(φ,λ,h)", p0, 24, 28, "teal")
    svg.text("North arc ≈ (M+h)dφ", p_n_tan, -154, -34, "indigo")
    svg.text("East arc ≈ (ν+h)cosφ dλ", p_e_tan, 22, 34, "teal")
    svg.text("Up: dh", p_u, 16, -32, "orange")
    svg.text_xy("v_N=(M+h)φ_dot  ⇒  φ_dot=v_N/(M+h)", 44, 525, "formula")
    svg.text_xy("v_E=(ν+h)cosφ λ_dot  ⇒  λ_dot=v_E/((ν+h)cosφ)", 44, 550, "formula")
    svg.text_xy("v_U=h_dot；M=a(1-e²)/(1-e²sin²φ)^(3/2)，ν=a/sqrt(1-e²sin²φ)", 44, 575, "formula")
    return svg.render()


def diagram_conventions() -> str:
    width, height = 980, 560
    out = svg_2d_header(width, height, "Simulator and FAA frame conventions")
    out.append('<text class="title" x="34" y="42">符号对齐：你的 simulator.py 与 FAA NED surface frame</text>')
    out.append('<text class="subtitle" x="34" y="66">两者都可用于右手局部空间，但水平轴顺序和航向角定义不同</text>')
    out.append('<rect class="accent" x="58" y="110" width="382" height="300" rx="10"/>')
    out.append('<rect class="warn" x="540" y="110" width="382" height="300" rx="10"/>')
    out.append('<text class="label" x="86" y="146">当前 simulator.py 约定（按 ENU 解释）</text>')
    out.append('<text class="label" x="568" y="146">FAA 2.8 surface frame 约定（NED）</text>')
    ox, oy = 230, 296
    out.append(f'<line class="east" x1="{ox}" y1="{oy}" x2="{ox + 125}" y2="{oy}"/>')
    out.append(f'<line class="north" x1="{ox}" y1="{oy}" x2="{ox}" y2="{oy - 125}"/>')
    out.append(f'<line class="up" x1="{ox}" y1="{oy}" x2="{ox - 74}" y2="{oy - 74}"/>')
    out.append(f'<path class="helper" d="M {ox + 58},{oy} A 58,58 0 0 0 {ox},{oy - 58}"/>')
    out.append(f'<text class="teal" x="{ox + 132}" y="{oy + 5}">x = E</text>')
    out.append(f'<text class="indigo" x="{ox - 26}" y="{oy - 137}">y = N</text>')
    out.append(f'<text class="orange" x="{ox - 128}" y="{oy - 86}">h = Up / altitude</text>')
    out.append(f'<text class="indigo" x="{ox + 42}" y="{oy - 42}">ψ: East → North</text>')
    out.append('<text class="formula" x="92" y="382">v_E=V cosγ cosψ</text>')
    out.append('<text class="formula" x="92" y="404">v_N=V cosγ sinψ</text>')
    ox2, oy2 = 710, 296
    out.append(f'<line class="north" x1="{ox2}" y1="{oy2}" x2="{ox2}" y2="{oy2 - 125}"/>')
    out.append(f'<line class="east" x1="{ox2}" y1="{oy2}" x2="{ox2 + 125}" y2="{oy2}"/>')
    out.append(f'<line class="down" x1="{ox2}" y1="{oy2}" x2="{ox2 - 74}" y2="{oy2 + 74}"/>')
    out.append(f'<path class="helper" d="M {ox2},{oy2 - 58} A 58,58 0 0 1 {ox2 + 58},{oy2}"/>')
    out.append(f'<text class="indigo" x="{ox2 - 34}" y="{oy2 - 137}">x_s = N</text>')
    out.append(f'<text class="teal" x="{ox2 + 132}" y="{oy2 + 5}">y_s = E</text>')
    out.append(f'<text class="magenta" x="{ox2 - 130}" y="{oy2 + 118}">z_s = Down</text>')
    out.append(f'<text class="indigo" x="{ox2 + 24}" y="{oy2 - 42}">χ: North → East</text>')
    out.append('<text class="formula" x="720" y="365">Vx=v_N=V cosγ cosχ</text>')
    out.append('<text class="formula" x="720" y="388">Vy=v_E=V cosγ sinχ</text>')
    out.append('<text class="formula" x="82" y="486">若沿用 simulator.py：χ = π/2 − ψ，且 χ_dot = −ψ_dot。</text>')
    out.append('<text class="formula" x="82" y="512">若改成航空常见 heading χ，建议同时调整转弯率符号，避免 bank 正负含义反掉。</text>')
    out.append("</svg>")
    return "\n".join(out)


def values_readme() -> str:
    phi = TEACHING_PHI
    return f"""# Generated surface-frame propagation diagram metadata

These SVG files are generated by `../generate_surface_frame_propagation_diagrams.py`.

- WGS 84 semi-major axis a: {WGS84_A_M:.1f} m
- WGS 84 inverse flattening: {WGS84_INV_F:.12f}
- WGS 84 first eccentricity squared e^2: {WGS84_E2:.14f}
- Teaching latitude phi: {TEACHING_PHI_DEG:.6f} deg
- Teaching longitude lambda: {TEACHING_LAMBDA_DEG:.6f} deg
- Meridian radius M at teaching latitude: {meridian_radius_over_a(phi) * WGS84_A_M:.3f} m
- Prime vertical radius nu at teaching latitude: {nu_over_a(phi) * WGS84_A_M:.3f} m
- Visual aircraft height arrow: {VISUAL_H_OVER_A:.3f} a, used only to make the local frame visible.
"""


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def main() -> None:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    write(ASSET_DIR / "01-surface-frame-architecture.svg", diagram_architecture())
    write(ASSET_DIR / "02-ecef-surface-frame.svg", diagram_surface_frame())
    write(ASSET_DIR / "03-geodetic-rate-patch.svg", diagram_rate_patch())
    write(ASSET_DIR / "04-simulator-convention-map.svg", diagram_conventions())
    write(ASSET_DIR / "README.md", values_readme())


if __name__ == "__main__":
    main()
