"""Compare the selectable collocation defect schemes on one problem.

The optimiser (``casadi_direct_collocation_optimizer``) supports five defect
"fitting equations":

    trapezoidal     – state piecewise-linear, 2nd order, cheapest
    hermiteSimpson  – state cubic (Simpson rule), 4th order, the default
    rk4             – RK4 integral defect, 4th order, playback-consistent
    reanchoredEnu   – re-anchored ENU RK4 step (the exact playback model), 4th
    localEnu        – fixed ENU step anchored at the target; a LOCAL approx
                      that drifts far from the anchor (see dynamics_comparison_30km)

trapezoidal/hermiteSimpson/rk4 collocate the continuous geodetic RHS; the ENU
schemes are shooting/integrator defects.  reanchoredEnu uses the discrete
re-anchored-ENU one-step map the frontend playback runs, so it matches the
playback's vector field exactly (no geodetic-vs-ENU model gap).  Here we replay
every scheme through a common fine GEODETIC integrator, so the ENU schemes show
a slightly larger residual than HS/rk4 (they are tuned to the ENU model, not
this geodetic reference) — their accuracy is checked in the test suite and in
the 30 km comparison instead.

This script solves the SAME feasible problem with each scheme and reports how
well the returned controls, when replayed through a fine integrator, land on
the target (the "playback consistency" — the practical accuracy that matters
for the frontend).  A feasible, on-manifold target is generated by forward-
propagating the nominal control, so every scheme converges and the comparison
is apples-to-apples.

Run:
    python -m collocation_scheme_comparison                 # A320 defaults
    python -m collocation_scheme_comparison --aircraft C172 --horizon 60
"""

from __future__ import annotations

import argparse
import io
import contextlib
import math
import sys
from pathlib import Path

import casadi as ca
import numpy as np

from geokit import kt_to_ms

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
_OPT_DIR = Path(__file__).resolve().parent
if str(_OPT_DIR) not in sys.path:
    sys.path.insert(0, str(_OPT_DIR))

from aircraft.aircraft_sets import A320, C172  # noqa: E402
from aerodynamic_model.common import GeodeticState  # noqa: E402
from aerodynamic_model.casadi_simulator import (  # noqa: E402
    aero_params_for_aircraft, make_geodetic_step_integrator,
)
from casadi_direct_collocation_optimizer import (  # noqa: E402
    CasadiDirectCollocationOptimizer, _DEFECT_SCHEMES,
)

_AIRCRAFT = {"A320": A320, "C172": C172}
_SCHEMES = list(_DEFECT_SCHEMES)  # all registered schemes (keep `orders` in sync)
_R = 6_371_000.0


def _horiz_m(lat, lon, ref):
    return _R * math.hypot(
        math.radians(lat - ref.latitude),
        math.radians(lon - ref.longitude) * math.cos(math.radians(ref.latitude)),
    )


def _aero_dm(aircraft):
    ap = aero_params_for_aircraft(aircraft)
    return ca.DM([ap.S, ap.Cl_max, ap.Cd0, ap.k, ap.stall_threshold, ap.k_stall])


def _feasible_target(aircraft, init, horizon):
    """Forward-propagate the nominal approach control to get an on-manifold
    target the optimiser can recover with any scheme."""
    step = make_geodetic_step_integrator(transport="approx")["step_func"]
    aero = _aero_dm(aircraft)
    u = ca.DM([aircraft.approach.thrust_guess_n, 0.0, 1.0])
    x = ca.DM([init.latitude, init.longitude, init.altitude,
               init.V, init.psi, init.gamma, init.m])
    for _ in range(int(horizon / 0.05)):
        x = step(x_geo=x, u=u, aero_params=aero, dt=0.05)["x_geo_next"]
    a = np.array(x).reshape(-1)
    return GeodeticState(a[0], a[1], a[2], a[3], a[4], a[5], aircraft.mass.max_takeoff_kg)


def _replay_terminal(aircraft, init, controls, horizon, dt=0.05):
    """Replay piecewise-constant controls through the fine geodetic integrator
    and return (terminal GeodeticState, min altitude)."""
    step = make_geodetic_step_integrator(transport="approx")["step_func"]
    aero = _aero_dm(aircraft)
    x = ca.DM([init.latitude, init.longitude, init.altitude,
               init.V, init.psi, init.gamma, init.m])
    seg = horizon / len(controls)
    min_alt = float("inf")
    for row in controls:
        u = ca.DM([float(row[0]), float(row[1]), float(row[2])])
        rem = seg
        while rem > 1e-9:
            h = min(dt, rem)
            x = step(x_geo=x, u=u, aero_params=aero, dt=h)["x_geo_next"]
            rem -= h
            min_alt = min(min_alt, float(x[2]))
    a = np.array(x).reshape(-1)
    return GeodeticState(a[0], a[1], a[2], a[3], a[4], a[5], aircraft.mass.max_takeoff_kg), min_alt


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--aircraft", choices=sorted(_AIRCRAFT), default="A320")
    parser.add_argument("--n-segments", type=int, default=10)
    parser.add_argument("--horizon", type=float, default=90.0, help="feasible duration (s)")
    args = parser.parse_args(argv)

    aircraft = _AIRCRAFT[args.aircraft]
    speed = kt_to_ms(aircraft.approach.reference_speed_kt) + 12.0
    init = GeodeticState(35.60, -78.50, 1500.0, speed, math.radians(40.0), math.radians(-3.0), aircraft.mass.max_takeoff_kg)
    target = _feasible_target(aircraft, init, args.horizon)

    print(f"\nCollocation defect-scheme comparison — aircraft={args.aircraft}, "
          f"N={args.n_segments}, horizon={args.horizon:.0f}s")
    print("Replaying each scheme's controls through a fine integrator:\n")
    print(f"  {'scheme':<16}{'order':>6}{'converged':>11}{'node→tgt[m]':>13}"
          f"{'PLAYBACK→tgt[m]':>17}{'replay min-alt[m]':>19}")
    print("  " + "-" * 82)

    orders = {"trapezoidal": 2, "hermiteSimpson": 4, "rk4": 4,
              "reanchoredEnu": 4, "localEnu": 4,
              "localEnuTrapezoidal": 2, "localEnuHermiteSimpson": 4}
    for scheme in _SCHEMES:
        opt = CasadiDirectCollocationOptimizer(
            n_segments=args.n_segments, dt=0.2, max_duration=args.horizon * 1.6,
            aircraft=aircraft, collocation_scheme=scheme,
        )
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                _, controls, states = opt.optimize_trajectory(init, target, duration=args.horizon)
            ok = bool(opt.solver.stats().get("success", False))
            node_miss = _horiz_m(states[-1][0], states[-1][1], target)
            pb, min_alt = _replay_terminal(aircraft, init, controls, args.horizon)
            print(f"  {scheme:<16}{orders.get(scheme, '?'):>6}{('yes' if ok else 'no'):>11}"
                  f"{node_miss:>13.3f}{_horiz_m(pb.latitude, pb.longitude, target):>17.2f}{min_alt:>19.1f}")
        except ValueError as exc:
            print(f"  {scheme:<16}{orders.get(scheme, '?'):>6}{'FAIL':>11}   {str(exc).split(': ')[-1][:40]}")

    print("\nInterpretation: every scheme pins its own NODES on the target (node→tgt≈0),")
    print("but replaying the controls reveals the scheme's true accuracy. The crude")
    print("trapezoidal (order 2) drifts the most; the higher-order hermiteSimpson and")
    print("rk4 (both order 4) are sub-metre. Which of HS/rk4 wins at a given mesh depends")
    print("on the case — order is an asymptotic (h→0) statement; at practical densities")
    print("HS is already excellent. Refine the mesh (smaller h) to see each scheme's")
    print("error shrink at its own rate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
