/// <reference types="vite/client" />
// This file tells TypeScript about Vite-specific globals like import.meta.env
// It is auto-generated by Vite project templates. Do not delete it.

// VITE_CESIUM_ION_TOKEN
interface ImportMetaEnv
{
    readonly VITE_CESIUM_ION_TOKEN:string;
}

interface ImportMeta {
    readonly env:ImportMetaEnv;
}