/* The paper figures: file name, kind and the suggested caption. The captions are on this page only, never in the image files. */
(function () {
  const TT = window.TT = window.TT || { demos: {} };
  TT.figs = {
    fig01_architecture: { n: 1, kind: 'diagram', alt: 'Block diagram of the two-tier model', caption: 'The two-tier model. The labeller reads sentences from observed tracks. The prior says one row of words for each aircraft. The executor flies only these words, and the judge classifies the flight. The post-training closes the loop with a reward. The letters mark the stage that builds each part.' },
    fig02_vocabulary_grids: { n: 2, kind: 'real data and sketch', alt: 'The grids of the five columns', caption: 'The grids of the vocabulary. (a) Heading words in 5° steps, relative to the course of the runway in force. (b) Tolerance ε of the 40 altitude levels, on three segments. (c) The four descent classes with their edges. (d) Speed words as steps of 5 m/s, and the speed that the executor flies at a_max = 1.4 m/s².' },
    fig03_sentence_example: { n: 3, kind: 'real data', alt: 'A real sentence on its flight', caption: 'A real sentence of an arrival to runway 23R of KRDU (train split, Δ = 4 s). (a) Plan view. (b) Height above the airport and the altitude words. (c) Ground speed and the speed words. (d) The words that each row says; orange marks correction words.' },
    fig04_executor_laws: { n: 4, kind: 'sketch', alt: 'The lateral, vertical and speed laws', caption: 'The three laws of the executor, in a kinematic sketch. (a)–(c) Lateral law: a heading word of 90°, the three rates and the bank. (d)–(e) Vertical law: a descent to a level with descent class 2. (f) Speed law: speed words in steps of 5 m/s.' },
    fig05_closed_loop_real: { n: 5, kind: 'real data', alt: 'Errors and correction words of a real flight', caption: 'The closed-loop reading on the flight of Fig. 3. (a) Lateral error and the heading correction words. (b) Vertical error, with H = 15 m and H_final = 10 m. (c) The observed words and the correction words of the heading and angle columns.' },
    fig06_corrections_effect: { n: 6, kind: 'sketch', alt: 'Paths and errors with and without correction words', caption: 'The effect of the correction words, in a sketch with a pilot model. (a) The observed path and the paths flown with and without corrections. (b) The lateral error against time; the dots are correction words.' },
    fig07_delta_grid: { n: 7, kind: 'real data', alt: 'Heading words on three row intervals', caption: 'The heading words of one real flight on the 2 s rows of the data and on the grids of Δ = 2, 4 and 8 s. Each word goes to the nearest row; the orange lines show the move of a word.' },
    fig08_prior_architecture: { n: 8, kind: 'diagram', alt: 'Network of the prior', caption: 'The network of the prior. The inputs are summed, pass four layers, and give a hidden state. Five heads say the words in the order of the columns, and each head reads the words that the earlier columns chose in the same row (purple arrows). The words of a row are inputs of the next row (purple loop), and the causal time attention reads the rows before it, so the prior is autoregressive over the columns and over the rows. A traffic attention in each layer reads the other aircraft (detail at the top); its output is zero when there is no other aircraft.' },
    fig09_procedure_masks: { n: 9, kind: 'real geometry', alt: 'Procedure masks on the final of KRDU 23R', caption: 'The procedure masks on the final of KRDU runway 23R (published values). (a) Inside the region, the lower edge blocks the low levels. (b) Before the join, after a dip below the entry height, the no-climb mask blocks levels above the aircraft, and the DA blocks the lowest level.' },
    fig10_decoding: { n: 10, kind: 'illustration', alt: 'One column of the speaker', caption: 'One column of the speaker. (a) The probabilities of the model; the masks block two words. (b) The probabilities after the masks. (c) The word is the one where the cumulative probability first passes the random number u. The probabilities are an illustration.' },
    fig11_cv_design: { n: 11, kind: 'diagram', alt: 'Cross-validation by airport', caption: 'Cross-validation by airport and the four steps of the campaign. (a) Each fold trains on four airports and reads the fifth. (b) The steps, with the number of training runs (31 in total).' },
    fig12_post_training_loop: { n: 12, kind: 'diagram', alt: 'The post-training loop with branch training', caption: 'The post-training loop with branch training, in a window of recorded traffic. The prior speaks for one aircraft under its masks, the executor flies, and the judges give the outcome, which gives the reward. The reward gives the advantages of the branch groups. The update has three terms: the clipped surrogate, the pull to the base model and a data term (teacher forcing on the landed sentences of the train days).' },
    fig13_branch_training: { n: 13, kind: 'illustration', alt: 'Branch groups of one window', caption: 'Branch training for one window whose first sentence failed. At each branch point, eight continuations start from a copy of the state. The advantage of a sentence is its reward minus the mean of its group. The outcomes of the continuations are a random illustration.' },
    fig14_traffic_features: { n: 14, kind: 'diagram', alt: 'Approach clock and relative geometry', caption: 'Traffic in the post-training. (a) The gap on the approach clock and the prediction of the speed-word mask. (b) The geometry that the edge features of another aircraft describe.' },
    fig15_judge_outcomes: { n: 15, kind: 'diagram', alt: 'The outcomes of the judge', caption: 'The outcomes of the judge, in the order in which it asks its questions. The first event is the outcome.' },
    fig16_window_kinds: { n: 16, kind: 'diagram', alt: 'The four kinds of window', caption: 'The four kinds of window of a round. (a) A real window. (b) Window A: one more flight is inserted, shifted to land within 180 s of the commanded flight. (c) Window D: the aircraft ahead is shifted in time by −120 s to +120 s. (d) Window B: the start of the commanded aircraft is moved by a turn of up to ±15°, a height change of up to ±300 m and a speed scale of 1 ± 0.1. The commanded aircraft is the one that speaks; the others fly their records.' },
    fig17_landed_training: { n: 17, kind: 'diagram', alt: 'The post-training loop with training on the landed sentences', caption: 'The post-training loop with training on the landed sentences. The top row is as in Fig. 12. For each window the model speaks several times and the landing of the highest reward is kept. The update is the log-likelihood of the kept sentences, with the pull to the base model and the data term.' },
    fig18_prior_layers: { n: 18, kind: 'diagram', alt: 'The input of a row, one layer and the five heads', caption: 'Inside the prior. (a) The input of a row: three kinds of input are added, and the candidate pool adds what the row reads of the candidate tokens; the token network that makes the tokens is a Linear layer, a GELU and a Linear layer. (b) One layer (four are stacked): the vector of the row is a rail, and each block adds to it; the causal time attention uses RoPE on the time in seconds, the traffic attention is an added module, and the feed-forward comes last. (c) The five heads in the order of the columns: each head reads the hidden state plus the embeddings of the words that the earlier columns said in the same row.' },
    fig19_traffic_attention: { n: 19, kind: 'diagram', alt: 'The traffic attention', caption: 'The traffic attention. Once for each step, the other aircraft become tokens: 20 numbers each go through a token network (Linear, GELU, Linear), once for each step. All the layers read these tokens. In each layer, the row attends to the tokens (four heads; the keys and values come from the tokens), and the result goes through a Linear layer that starts at zero and is added to the row. Where a row has no other aircraft, the output is zero.' },
    fig20_multi_round: { n: 20, kind: 'diagram', alt: 'One round of stage D, and the loop inside it', caption: 'Stage D. (a) One round: the windows are drawn; every commanded aircraft of a window speaks at once (first pass) and the reward W is the sum of the aircraft’s rewards; a window in which every aircraft landed gives no sample; the other windows are spoken again with one aircraft varied (second pass), the advantage is W less the group mean on the varied aircraft’s later rows, and the update is the loss of stage C. (b) The loop that steps 2 and 4 run, one row at a time: the aircraft join at their own first rows, each commanded aircraft gets its tokens, the prior speaks for all of them at once, the executor flies each, and the separation judge makes a responsible aircraft silent. Grey: data. Blue: speaking, no gradient. Red: learning.' },
    fig21_random_number: { n: 21, kind: 'illustration', alt: 'A random number picks a word', caption: 'How a random number picks a word. The words of one column are laid on a line from 0 to 1, each with a piece as long as its probability, and the word whose piece holds the random number u is said. With the same pieces, the same u gives the same word (top). When the situation changes and the probabilities change, the same u can fall in another word (bottom). The probabilities are made up.' },
    fig22_window_branches: { n: 22, kind: 'illustration', alt: 'How the sentences of a window branch and affect each other', caption: 'How the sentences of one window branch and affect each other during the training, for three commanded aircraft, in a time-distance diagram: an aircraft is a line that goes down to the threshold, a steep line is a fast aircraft, and the gap between two aircraft is the vertical distance between their lines. Left: the first sentence, in which aircraft v is too close behind aircraft 2 (a loss). Middle and right: two continuations from the same branch point. Only v has new random numbers (thick line). The other aircraft keep theirs, but their probabilities change because v changed, and they answer (dashed arrows). W is the number of landings, and the advantage is W less the group mean (2); it applies to v’s rows after the branch point only. The lines are made up.' },
    fig23_window_tree: { n: 23, kind: 'illustration', alt: 'The tree of the sentences made from one window', caption: 'The tree of the sentences that the training makes from one window of three commanded aircraft (v1 and v2 failed, v3 landed). One group is made for each varied aircraft (here v1 and v2) and each of its branch points (b1, b2, b3). The group of v1 at b2 is opened: the first sentence and the continuations, each of which copies the state of the whole window at b2 and gives new random numbers to v1 only. A row shows the outcomes of v1, v2 and v3 (cross: failed, dot: landed), the reward W (the number of landings) and the advantage (W less the mean of the group, 1.25), which applies to the rows of v1 after b2 only. A ring marks an aircraft that keeps its random numbers but changed its outcome because v1 changed. The outcomes are made up.' }
  };
  TT.buildFigures = () => {
    document.querySelectorAll('figure.paper[data-fig]').forEach(f => {
      const id = f.dataset.fig, d = TT.figs[id]; if (!d) { f.textContent = 'missing figure ' + id; return; }
      f.replaceChildren(
        TT.el('div', { class: 'row', style: 'margin:0 0 6px' }, [TT.el('span', { class: 'pill', text: 'Paper figure' }), TT.el('span', { class: 'fignum', text: 'Figure ' + d.n }), TT.el('span', { class: 'src', text: d.kind })]),
        TT.el('img', { src: `figures/png/${id}.png`, alt: d.alt, loading: 'lazy' }),
        TT.el('div', { class: 'links' }, [TT.el('span', {}, [TT.el('b', { text: 'Files: ' })]), TT.el('a', { href: `figures/png/${id}.png`, text: id + '.png (300 dpi)' }), TT.el('a', { href: `figures/pdf/${id}.pdf`, text: id + '.pdf (vector)' })]),
        TT.el('details', {}, [TT.el('summary', { text: 'Suggested caption (not in the image)' }), TT.el('p', { text: d.caption })]));
    });
  };
})();
